defmodule Todo.Metrics do
  @moduledoc """
  """
  use Task

  @doc """
  main purpose of start_link is to allow OTP compatible process to run under
  supervisor.

  Dev Notes:
  The supervisor picks up exactly this function because it is precisely that
  is pointed to, by created child_spec, which is generated by default in the
  child_spec/1 function, which is injected into this module by "use Task"
  """
  def start_link(_arg), do: Task.start_link(&loop/0)

  defp loop() do
    Process.sleep(sleep_interval())
    IO.inspect(collect_metrics())
    loop()
  end

  defp collect_metrics() do
    [
      memory_usage: :erlang.memory(:total),
      process_count: :erlang.system_info(:process_count)
    ]
  end

  @spec sleep_interval() :: Iteger.t()
  defp sleep_interval() do
    settings = Application.fetch_env!(:todo, :metrics)
    Keyword.fetch!(settings, :interval)
  end
end
